### ISSUE TITLE
Soft lock caused by Gatherer with Replay the Spire

### ISSUE THREAD

**Issue by MadeForComplaints** [Celicath/GathererMod#2]
I was playing by Ironclad and I recently obtained Hand Mirror from Replay the Spire. I had a doubt in my hand and I ended my turn only to have the doubt infinitely apply weakness while Hand mirror also infinity proc. This would've been a Replay the Spire problem if I didn't check the logs to see that your mod was causing the problem.

_The lines of text that was repeated the entire time_
00:41:23.741 DEBUG the_gatherer.GathererMod> receivePowersModified started.
00:41:23.749 DEBUG the_gatherer.GathererMod> receivePowersModified finished.
00:41:23.821 INFO basemod.BaseMod> publish on post power apply
00:41:23.822 INFO basemod.BaseMod> powers modified

I can't go back any farther than that as the log reached character limit somehow.

Mod List Just incase
Base Mod
Fetch
StSLib
Blakk
Conspire
Super Fast Mode
The Beaked
Better Rewards
Hubris
Mad Scientist
RNG!
Shop Mod
Blackbeard
Disciple
Construct
Infinite Spire
Warrior
Mystic
Yuyoko
Witch
Friendly Minons
Marisa
Yohane
Relic Relevance Reorder
Replay the Spire
Gatherer

**Comment by Celicath** [comment]
This softlock issue is actually Replay the Spire's. Gatherer is just printing some logs and does not do anything in this particular case. I'll let you know when it is fixed and close.

**Comment by Celicath** [comment]
Seems to be fixed with Replay the Spire 1.2.5 release.
