### ISSUE TITLE
Bomber Form's 1 LEP per turn doesn't stack with multiple Bomber Forms

### ISSUE THREAD

**Issue by SilentJ28** [Celicath/GathererMod#6]
I have 2 Bomber Form+s. I get +4 LEP dmg per potion, but only 1 LEP per turn

**Comment by Celicath** [comment]
This is actally my intention, to prevent it from being too explosive when stacked. The text doesn't tell you this though. I've considered many texts, but it's hard to explain this in a good way when it only partially stacks and the description is already too long. I briefly considered 'gain LEP only when your sack is empty' but ot sucks gameplay-wise and does not clear confusion perfectly.

Come to think about this, I can add a tooltip on it. Which isn't ideal, but it works I think.
