### ISSUE TITLE
Stuck in excess potions screen

### ISSUE THREAD

**Issue by STSsadoni** [Celicath/GathererMod#9]
Not sure what happened, but I somehow ended up with cards that choose from the hand instead going to the excess lesser potion screen.  It doesn't show any potions there to choose, so it softlocks the run.  Screenshot attached.
![gathererbug](https://user-images.githubusercontent.com/46309926/50721664-09520180-1078-11e9-8be7-826eff9e5490.png)

**Comment by Celicath** [comment]
Sorry for this bug. It happens when you gain 2 or more potions simultaneously when your bag is full, then use cards like Centralize, Wool gloves, etc. It will be fixed in the next patch. Before then, you can fix it by completely turning off the game and continue the run.
